import Axios from "axios";
import { PayloadBase } from "../base";

// Generated by https://quicktype.io

export interface INoteFoldResp {
    data: INoteFold[];
    status: number;
}

export interface INoteFold {
    create_time: string;
    id: string;
    name: string;
    uid: string;
}


interface IGetFolderPayload extends PayloadBase {
    uid: string
}

export async function getFolder(payload: IGetFolderPayload) {
    return Axios.get<INoteFoldResp>(`https://argusuat.perspectivar.com:8078/note_folder/query?uid=${payload.uid}`)
}
