// Generated by https://quicktype.io

import Axios from 'axios'
import { PayloadBase } from '../base'
import Constant from '../constant/constant'
import { AuthedHeader } from '../login'

export interface INoteDettail {
    annex: null
    data: Data
    filename: string
    id: string
    isLoding: number
    ispublic: null
    money: null
    spenttime: number
    userid: string
}

export interface Data {
    beforvideoUrl: string
    fileid: string
    filetype: string
    fsize: number
    imgTxt?: ImgTxt[]
    ppt: Ppt[]
    soundWord: SoundWord[]
    status: string
    videoUrl: string
}

export interface ImgTxt {
    bg: number
    img: string
    onebest: string
    words: string
}

export interface Ppt {
    base?: string
    endTime: number
    image: string
    startTime: number
    timestamp: number
    wordsShow: WordsShow[]
}

export interface WordsShow {
    confidence: number
    rect: Rect
    word: string
}

export interface Rect {
    heightInPixel: number
    leftOffsetInPixel: number
    topOffsetInPixel: number
    widthInPixel: number
}

export interface SoundWord {
    bg: string
    ed: string
    onebest: string
    speaker: string
}


interface IGetDetails extends PayloadBase {
    notesid: string

}
export async function GetNoteDetails(payload: IGetDetails) {
    return Axios.get<INoteDettail>(
        `${Constant.api.host}/fix_user/query_single_notes_detail?fileid=${payload.notesid}`,
        {
            headers: AuthedHeader(),
            timeout: 2000,
            cancelToken: payload.cToken
        }
    )
}
