import Axios from 'axios'
import Constant from '../constant/constant'
import { AuthedHeader } from '../login'

// Generated by https://quicktype.io

export interface INotes {
    id: string
    userid: string
    filename: string
    pic: string
    spenttime: number | null
    annex: null
    isLoading: number
    ispublic: number | null
}

export async function GetNotes(payload: { userid: string }) {
    return Axios.get<INotes[]>(
        `${Constant.api.host}/fix_user/query_user_notes_list?userid=${payload.userid}`,
        { headers: AuthedHeader() }
    )
}
