import Axios from 'axios'
import Constant from '../constant/constant'
import { AuthedHeader } from '../login'

// Generated by https://quicktype.io

export interface INotes {
    id: string
    userid: string
    filename: string
    pic: string
    spenttime: number | null
    annex: null
    isLoading: number
    ispublic: number | null
}

// Generated by https://quicktype.io

export interface ISingleNoteDetail {
    annex: null
    data: string
    filename: string
    id: string
    isLoding: number
    ispublic: null
    money: null
    spenttime: null
    userid: string
}

export async function GetNotes(payload: { userid: string }) {
    return Axios.get<INotes[]>(
        `${Constant.api.host}/fix_user/query_user_notes_list?userid=${payload.userid}`,
        { headers: AuthedHeader() }
    )
}

export async function query_single_video(params: { id: string }) {
    return Axios.get<ISingleNoteDetail>(
        `${Constant.api.host}/fix_user/query_single_notes_detail?fileid=${params.id}`,
        { headers: AuthedHeader() }
    )
}
